version: '2'
services:
  mariadb:
    image: "mariadb:latest"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=logitch
    ports:
      - "3306:3306"